### ISSUE TITLE
TODO: the big list

### ISSUE THREAD

**Issue by Draconizations** [Spectralitree/pk-webs-svelte#3]
Just the list of features that I want to implement still:

- [x] refactor the api handling. Remove most of the methods and just leave basic error/status handling and types.
- [x] add ratelimit handling to the api
- [x] add the new group privacy settings to editing group privacy
- [x] add member/group creation (ideally not via a popup like in the old site, maybe an expandable accordion?)
- [x] individual member and group pages, both public and private
- [x] editing on the private individual pages, similar/identical to editing in the list
- [x] a full group member list (like the current system list) on private group pages
- [ ] most visual settings from the old site carried over to this one
- [ ] templates, hopefully not limited to 3 like on the old site? maybe being able to add/remove more templates as you please
- [ ] a faq, not sure where exactly tho

most of the above was just for feature parity with the old site, these ones are completely new

- [ ] viewing your current fronters (potentially on the home page, where "cool stuff will go here" is now)
- [ ] a switches tab where you can view your front history, and view/edit your latest switch (or older switches?), not sure if the front history should be available publicly too

some things im not too sure about: viewing and editing server specific settings and bulk things like privating all members at once. The former I'm not sure how to fit in, the latter I just am not confident enough in implementing myself

this list might be edited in the future if any new things come to mind
